// <auto-generated />
using Bot.Resources.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bot.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20190409123224_Migration")]
    partial class Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("Bot.Resources.Database.Items", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IName");

                    b.Property<int>("Price");

                    b.HasKey("ItemID");

                    b.ToTable("items");
                });

            modelBuilder.Entity("Bot.Resources.Database.MyUser", b =>
                {
                    b.Property<ulong>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Coins");

                    b.HasKey("UserID");

                    b.ToTable("myUser");
                });

            modelBuilder.Entity("Bot.Resources.Database.UserItems", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<int>("ItemID");

                    b.Property<ulong>("UserID");

                    b.HasKey("ID");

                    b.ToTable("userItems");
                });
#pragma warning restore 612, 618
        }
    }
}
