// <auto-generated />
using Bot.Resources.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bot.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    partial class SqliteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("Bot.Resources.Database.Items", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IName");

                    b.Property<int>("Price");

                    b.HasKey("ItemID");

                    b.ToTable("items");
                });

            modelBuilder.Entity("Bot.Resources.Database.MyBlacklist", b =>
                {
                    b.Property<int>("block_id")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("UserID");

                    b.HasKey("block_id");

                    b.ToTable("myblacklist");
                });

            modelBuilder.Entity("Bot.Resources.Database.MyUser", b =>
                {
                    b.Property<ulong>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Coins");

                    b.HasKey("UserID");

                    b.ToTable("myUser");
                });

            modelBuilder.Entity("Bot.Resources.Database.Pets", b =>
                {
                    b.Property<int>("PetID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("affection");

                    b.Property<int>("price");

                    b.HasKey("PetID");

                    b.ToTable("pets");
                });

            modelBuilder.Entity("Bot.Resources.Database.UserItems", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<int>("ItemID");

                    b.Property<ulong>("UserID");

                    b.HasKey("ID");

                    b.ToTable("userItems");
                });

            modelBuilder.Entity("Bot.Resources.Database.UserPets", b =>
                {
                    b.Property<ulong>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PetID");

                    b.Property<string>("PetName");

                    b.Property<int>("affection");

                    b.HasKey("UserID");

                    b.ToTable("userPets");
                });
#pragma warning restore 612, 618
        }
    }
}
